
/* AUTO-GENERATED by gen_isr_tables.py, do not edit! */

#include <toolchain.h>
#include <linker/sections.h>
#include <sw_isr_table.h>

extern void _irq_spurious(void *unused);
extern void _power_clock_isr(void *arg);
extern void radio_nrf5_isr(void *arg);
extern void _isr_wrapper(void);

u32_t __irq_vector_table _irq_vector_table[48] = {
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&radio_nrf5_isr, // 0x1450b,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
	(uint32_t)&_isr_wrapper,   //0x1109,
};
extern void gpio_nrf5_port_isr(void *arg);
extern void isr_rand(void *arg);
extern void swi4_nrf5_isr(void *arg);
extern void rtc0_nrf5_isr(void *arg);
extern void rtc1_nrf5_isr(void *arg);
extern struct device __device_entropy_nrf5;
//extern const void  * const device_entropy_nrf5;


struct _isr_table_entry __sw_isr_table _sw_isr_table[48] = {
	{(void *)0x0, (void *)&_power_clock_isr}, // 0x1e5d},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&gpio_nrf5_port_isr},//0x2171},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&rtc0_nrf5_isr},    //0x144d1},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
//	{(void *)0x20004494, (void *)&isr_rand}, //0x2415},
	{(void *)&__device_entropy_nrf5, (void *)&isr_rand}, //0x2415},
//	{device_entropy_nrf5, (void *)&isr_rand}, //0x2415},
//	{(void *), (void *)&isr_rand}, //0x2415},
//	{(void *)0x20004494, (void *)0x2415},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&rtc1_nrf5_isr},    //0x2555},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&swi4_nrf5_isr},    //0x14505},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious},    //0xf55},
	{(void *)0x0, (void *)&_irq_spurious}    //0xf55},
};
